name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - run: cargo install --git https://github.com/Piturnah/shovel-ssg
    - uses: actions/checkout@v3
      with:
        ref: dist
    - run: git fetch origin main
    - run: git reset --hard origin/main
    - run: shovel
    - run: find . -not -path "./.git/*" -not -name ".git" -not -path "./_build/*" -not -name "_build" -delete
    - run: "mv _build/* _build/.* . || :"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Update build
        branch: ci/build
        delete-branch: true
        title: Update build
        base: dist
