name: CI

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6.6'
          cabal-version: '3.12.1.0'
      - uses: actions/checkout@v3
      - run: cabal new-run site build
      - run: find . -not -path "./.git/*" -not -name ".git" -not -path "./_site/*" -not -name "_site" -delete
      - run: "mv _site/* _site/.* . || :"
      - run: git config --global user.email "noreply@github.com"
      - run: git config --global user.name "GitHub"
      - run: git checkout -b dist
      - run: git add .
      - run: git commit -m "Update build"
      - run: git rebase --root
      - run: git push origin dist --force
